name: robogames
version: '${project.version}'
main: com.roboter5123.robogames.RoboGames
api-version: '1.20'
commands:
  robogames:
    description: "Main command for RoboGames"
    usage: /<command> <subcommand> [args]
  arena:
    description: "Main command for editing RoboGames arenas"
    usage: /<command> <subcommand> [args]
permissions:
  robogames.game.join:
    description: "Allows you to join the game in roboGames"
    default: true
  robogames.game.leave:
    description: "Allows you to join the game in roboGames"
    default: true
  robogames.game.start:
    description: "Allows you to start the game in roboGames"
    default: op
  robogames.game.end:
    description: "Allows you to forcefully end the game in roboGames"
    default: op
  robogames.arena.select:
    description: "Allows you to select an arena in roboGames"
    default: op
  robogames.arena.create:
    description: "Allows you to create an arena in roboGames"
    default: op
  robogames.arena.setspawn:
    description: "Allows you to set spawnpoints for arenas in roboGames"
    default: op
